set_property IOSTANDARD LVCMOS33 [get_ports ENET0_GMII_RX_CLK_0]
set_property PACKAGE_PIN U14 [get_ports ENET0_GMII_RX_CLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports {enet0_gmii_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enet0_gmii_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enet0_gmii_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enet0_gmii_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TX_EN_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enet0_gmii_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enet0_gmii_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enet0_gmii_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enet0_gmii_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ENET0_GMII_RX_DV_0]
set_property PACKAGE_PIN Y17 [get_ports {enet0_gmii_rxd[3]}]
set_property PACKAGE_PIN V17 [get_ports {enet0_gmii_rxd[2]}]
set_property PACKAGE_PIN V16 [get_ports {enet0_gmii_rxd[1]}]
set_property PACKAGE_PIN Y16 [get_ports {enet0_gmii_rxd[0]}]
set_property PACKAGE_PIN U15 [get_ports ENET0_GMII_TX_CLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports ENET0_GMII_TX_CLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports FCLK_CLK1_0]
set_property PACKAGE_PIN U18 [get_ports FCLK_CLK1_0]
set_property PACKAGE_PIN W19 [get_ports {ENET0_GMII_TX_EN_0[0]}]
set_property PACKAGE_PIN Y19 [get_ports {enet0_gmii_txd[3]}]
set_property PACKAGE_PIN V18 [get_ports {enet0_gmii_txd[2]}]
set_property PACKAGE_PIN Y18 [get_ports {enet0_gmii_txd[1]}]
set_property PACKAGE_PIN W18 [get_ports {enet0_gmii_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_ETHERNET_0_0_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_ETHERNET_0_0_mdio_io]
set_property PACKAGE_PIN W15 [get_ports MDIO_ETHERNET_0_0_mdc]
set_property PACKAGE_PIN Y14 [get_ports MDIO_ETHERNET_0_0_mdio_io]
set_property PACKAGE_PIN W16 [get_ports ENET0_GMII_RX_DV_0]

set_property PACKAGE_PIN W14 [get_ports {GPIO_0_0_tri_io[0]}]
#set_property PACKAGE_PIN W13 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {Blue_Dout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue_Dout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue_Dout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue_Dout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue_Dout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue_Dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue_Dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue_Dout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green_Dout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green_Dout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green_Dout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green_Dout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green_Dout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green_Dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green_Dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green_Dout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red_Dout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red_Dout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red_Dout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red_Dout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red_Dout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red_Dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red_Dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red_Dout[0]}]

set_property PACKAGE_PIN U20 [get_ports {Blue_Dout[7]}]
set_property PACKAGE_PIN T20 [get_ports {Blue_Dout[6]}]
set_property PACKAGE_PIN P19 [get_ports {Blue_Dout[5]}]
set_property PACKAGE_PIN R19 [get_ports {Blue_Dout[4]}]
set_property PACKAGE_PIN R18 [get_ports {Blue_Dout[3]}]
set_property PACKAGE_PIN P20 [get_ports {Blue_Dout[2]}]
set_property PACKAGE_PIN N17 [get_ports {Blue_Dout[1]}]
set_property PACKAGE_PIN M17 [get_ports {Blue_Dout[0]}]
set_property PACKAGE_PIN P18 [get_ports {Green_Dout[7]}]
set_property PACKAGE_PIN N20 [get_ports {Green_Dout[6]}]
set_property PACKAGE_PIN M19 [get_ports {Green_Dout[5]}]
set_property PACKAGE_PIN L17 [get_ports {Green_Dout[4]}]
set_property PACKAGE_PIN M20 [get_ports {Green_Dout[3]}]
set_property PACKAGE_PIN L20 [get_ports {Green_Dout[2]}]
set_property PACKAGE_PIN L19 [get_ports {Green_Dout[0]}]
set_property PACKAGE_PIN M18 [get_ports {Green_Dout[1]}]
set_property PACKAGE_PIN L16 [get_ports {Red_Dout[7]}]
set_property PACKAGE_PIN J20 [get_ports {Red_Dout[6]}]
set_property PACKAGE_PIN K19 [get_ports {Red_Dout[5]}]
set_property PACKAGE_PIN K18 [get_ports {Red_Dout[4]}]
set_property PACKAGE_PIN J19 [get_ports {Red_Dout[3]}]
set_property PACKAGE_PIN H20 [get_ports {Red_Dout[2]}]
set_property PACKAGE_PIN G19 [get_ports {Red_Dout[1]}]
set_property PACKAGE_PIN J18 [get_ports {Red_Dout[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports vid_hsync_0]
set_property IOSTANDARD LVCMOS33 [get_ports vid_vsync_0]
set_property PACKAGE_PIN V20 [get_ports vid_vsync_0]
set_property PACKAGE_PIN U19 [get_ports vid_hsync_0]

set_property IOSTANDARD LVCMOS33 [get_ports Video_locked]
set_property PACKAGE_PIN W13 [get_ports Video_locked]

set_property IOSTANDARD LVCMOS33 [get_ports {H_Blank_n[0]}]
set_property PACKAGE_PIN G20 [get_ports {H_Blank_n[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports pix_clk_out1_0]
set_property PACKAGE_PIN T19 [get_ports pix_clk_out1_0]

set_property PACKAGE_PIN T10 [get_ports {GPIO_0_0_tri_io[1]}]

set_property MARK_DEBUG false [get_nets {H_Blank_n_OBUF[0]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list Zynq_proc_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {Zynq_proc_i/v_tpg_0/m_axis_video_TKEEP[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe1]
set_property port_width 24 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[0]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[1]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[2]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[3]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[4]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[5]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[6]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[7]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[8]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[9]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[10]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[11]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[12]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[13]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[14]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[15]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[16]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[17]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[18]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[19]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[20]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[21]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[22]} {Zynq_proc_i/v_axi4s_vid_out_0_vid_data[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe2]
set_property port_width 24 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[0]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[1]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[2]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[3]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[4]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[5]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[6]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[7]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[8]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[9]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[10]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[11]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[12]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[13]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[14]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[15]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[16]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[17]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[18]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[19]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[20]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[21]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[22]} {Zynq_proc_i/v_tpg_0_m_axis_video_TDATA[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {H_Blank_n_OBUF[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list Zynq_proc_i/v_tc_0/gen_clken]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list Zynq_proc_i/v_axi4s_vid_out_0_vid_hblank]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list Zynq_proc_i/v_axi4s_vid_out_0_vid_vblank]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list Zynq_proc_i/v_tc_0_vtiming_out_ACTIVE_VIDEO]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list Zynq_proc_i/v_tc_0_vtiming_out_HBLANK]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list Zynq_proc_i/v_tc_0_vtiming_out_HSYNC]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list Zynq_proc_i/v_tc_0_vtiming_out_VBLANK]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list Zynq_proc_i/v_tc_0_vtiming_out_VSYNC]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list Zynq_proc_i/v_axi4s_vid_out_0/vid_active_video]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list vid_hsync_0_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list vid_vsync_0_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list Zynq_proc_i/v_tpg_0_m_axis_video_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list Zynq_proc_i/v_tpg_0_m_axis_video_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list Zynq_proc_i/v_tpg_0_m_axis_video_TUSER]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list Zynq_proc_i/v_tpg_0_m_axis_video_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
